### ISSUE TITLE
"rss", "available", "unused" memory metrics are always zero

### ISSUE THREAD

**Issue by dgarth** [intelsdi-x/snap-plugin-collector-libvirt#38]
The memory metrics "unused", "available" and "rss" are always reported as 0. When using `virsh dommemstat <domain_name>` directly I get the expected non-zero readouts.

**Environment**
This plugin (the [linux/x86_64 build](https://s3-us-west-2.amazonaws.com/snap.ci.snap-telemetry.io/plugins/snap-plugin-collector-libvirt/latest/linux/x86_64/snap-plugin-collector-libvirt) from the [plugin-catalog](https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_CATALOG.md)) 
CentOS 7 (Kernel 3.10.0-327.36.3.el7.x86_64)
Snap v0.16.1-beta
OpenStack Liberty (via Devstack)
Libvirt 1.2.17-13.el7_2.5
qemu-kvm 10:2.3.0-31

**Comment by sandlbn** [comment]
Fixed in #36

**Comment by dgarth** [comment]
Using the [build from travis](https://s3-us-west-2.amazonaws.com/snap.ci.snap-telemetry.io/plugins/snap-plugin-collector-libvirt/latest_build/linux/x86_64/snap-plugin-collector-libvirt) (is this the correct version?) this problem still persists.

```
$ sudo virsh dommemstat instance-00000001
actual 2097152
swap_in 0
swap_out 0
major_fault 684
minor_fault 5486756
unused 1465420
available 1883980
rss 934796
```

"actual", "major_fault" and "minor_fault" are reported correctly by snap. "unused", "available" and "rss" are still 0.

```
libvirt.x86_64                       1.2.17-13.el7_2.5
libvirt-daemon-driver-qemu.x86_64    1.2.17-13.el7_2.5 
qemu-common.x86_64                   2:2.0.0-1.el7.6
qemu-img-ev.x86_64                   10:2.3.0-31.el7.16.1
qemu-kvm-common-ev.x86_64            10:2.3.0-31.el7.16.1
qemu-kvm-ev.x86_64                   10:2.3.0-31.el7.16.1
qemu-system-x86.x86_64               2:2.0.0-1.el7.6 
```

The VM is started via `qemu-kvm` and `accel=kvm` is passed so it should be running on KVM.

**Comment by IzabellaRaulin** [comment]
+1, Another user has similar issue 

@diziup wrote:

> Hi,

> We have tried the new plugin and the metrics returned are still 0.
> In contrast, we have configured our VM's so that virsh now fetches them with values:
> `virsh dommemstat l3fwd-1`
> actual 6291456
> swap_in 0
> swap_out 0
> major_fault 635
> minor_fault 136290
> unused 3827484
> available 6110524
> rss 2866048
> 
> Can you please elaborate on the exact way that libvirt plugin retrieves these metrics?
> perhaps we can reproduce them in our machine.

>### The test output
> [memOut.txt](https://github.com/intelsdi-x/snap-plugin-collector-libvirt/files/629366/memOut.txt)
> [memOut.txt](https://github.com/intelsdi-x/snap-plugin-collector-libvirt/files/629365/memOut.txt)
> 
> ### The host configuration are attached above
> **Host:**
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04.1 LTS
> Release:        16.04
> Codename:       xenial
> 
> Linux david 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
> 
> 
> **meminfo**
> MemTotal:       32826488 kB
> MemFree:         4245432 kB
> MemAvailable:   16070628 kB
> Buffers:          223048 kB
> Cached:         11553680 kB
> SwapCached:        70376 kB
> Active:         23311404 kB
> Inactive:        4055460 kB
> Active(anon):   15544460 kB
> Inactive(anon):    70444 kB
> Active(file):    7766944 kB
> Inactive(file):  3985016 kB
> Unevictable:        3660 kB
> Mlocked:            3660 kB
> SwapTotal:      33457148 kB
> SwapFree:       33356880 kB
> Dirty:               224 kB
> Writeback:             0 kB
> AnonPages:      15534096 kB
> Mapped:           126304 kB
> Shmem:             22320 kB
> Slab:             750680 kB
> SReclaimable:     480120 kB
> SUnreclaim:       270560 kB
> KernelStack:       11472 kB
> PageTables:        57432 kB
> NFS_Unstable:          0 kB
> Bounce:                0 kB
> WritebackTmp:          0 kB
> CommitLimit:    49870392 kB
> Committed_AS:   35036796 kB
> VmallocTotal:   34359738367 kB
> VmallocUsed:           0 kB
> VmallocChunk:          0 kB
> HardwareCorrupted:     0 kB
> AnonHugePages:  12926976 kB
> CmaTotal:              0 kB
> CmaFree:               0 kB
> HugePages_Total:       0
> HugePages_Free:        0
> HugePages_Rsvd:        0
> HugePages_Surp:        0
> Hugepagesize:       2048 kB
> DirectMap4k:      373484 kB
> DirectMap2M:    20502528 kB
> DirectMap1G:    14680064 kB
> 
> 
> **cpu:**
> there are 20 virtual cpu's with the following configuration:
> processor       : 19
> vendor_id       : GenuineIntel
> cpu family      : 6
> model           : 79
> model name      : Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz
> stepping        : 1
> microcode       : 0xb000014
> cpu MHz         : 1200.093
> cache size      : 25600 KB
> physical id     : 0
> siblings        : 20
> core id         : 12
> cpu cores       : 10
> apicid          : 25
> initial apicid  : 25
> fpu             : yes
> fpu_exception   : yes
> cpuid level     : 20
> wp              : yes
> flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts
> bugs            :
> bogomips        : 4800.07
> clflush size    : 64
> cache_alignment : 64
> address sizes   : 46 bits physical, 48 bits virtual
> power management:
> 
> 
> **The host model:** Dell r630

See the whole discussion on https://github.com/intelsdi-x/snap-plugin-collector-libvirt/issues/43

**Comment by diziup** [comment]
Any update on the issue?

**Comment by sandlbn** [comment]
@dgarth bug is fixed now and version 12 of plugin is released. Enjoy. https://github.com/intelsdi-x/snap-plugin-collector-libvirt/releases
